#!/usr/bin/env python3
"""
Renders index.template.html + site.config.json into index.html, and
generates assets/js/site-config.js so main.js can read the same values.

Usage: python3 build.py
Edit site.config.json (and swap files in Media/ + assets/img/), then re-run.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
CONFIG_PATH = ROOT / "site.config.json"
TEMPLATE_PATH = ROOT / "index.template.html"
OUTPUT_HTML_PATH = ROOT / "index.html"
OUTPUT_JS_PATH = ROOT / "assets" / "js" / "site-config.js"


def derive_phone_digits(phone_e164):
    digits = re.sub(r"\D", "", phone_e164)
    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]
    return digits


def main():
    config = json.loads(CONFIG_PATH.read_text())
    config["serviceArea"] = f"{config['serviceAreaCity']} & Surrounding Areas"
    config["phoneDigits"] = derive_phone_digits(config["phoneE164"])

    tokens = {
        "PAGE_TITLE": config["pageTitle"],
        "META_DESCRIPTION": config["metaDescription"],
        "BUSINESS_NAME": config["businessName"],
        "PHONE_E164": config["phoneE164"],
        "PHONE_DISPLAY": config["phoneDisplay"],
        "SERVICE_AREA_CITY": config["serviceAreaCity"],
        "SERVICE_AREA_STATE": config["serviceAreaState"],
        "STARTING_PRICE": config["startingPrice"],
        "COPYRIGHT_YEAR": config["copyrightYear"],
    }

    html = TEMPLATE_PATH.read_text()
    for key, value in tokens.items():
        html = html.replace("{{" + key + "}}", value)

    leftover = re.findall(r"\{\{[A-Z_]+\}\}", html)
    if leftover:
        raise SystemExit(f"Unreplaced tokens in template: {sorted(set(leftover))}")

    header = (
        "<!--\n"
        "  AUTO-GENERATED from index.template.html + site.config.json.\n"
        "  Do not hand-edit this file directly — edit index.template.html for\n"
        "  structure/copy, edit site.config.json for business details, then run\n"
        "  `python3 build.py` to regenerate this file.\n"
        "-->\n"
    )
    OUTPUT_HTML_PATH.write_text(header + html)

    js = "// AUTO-GENERATED by build.py from site.config.json. Do not hand-edit.\n"
    js += "window.SITE_CONFIG = " + json.dumps(config, indent=2, ensure_ascii=False) + ";\n"
    OUTPUT_JS_PATH.write_text(js)

    print(f"Built {OUTPUT_HTML_PATH.name} and {OUTPUT_JS_PATH.relative_to(ROOT)} for '{config['businessName']}'.")


if __name__ == "__main__":
    main()
